### ISSUE TITLE
'ArduinoFFT' was not declared in this scope

### ISSUE THREAD

**Issue by wilson3682** [HorstBaerbel/HubAlyzer#1]
Hi, when I try to compile the sketch, this is the error I'm getting. Do you know what could be happening? All libraries needed have been installed including the arduinoFFT library.

line 122   auto fft = ArduinoFFT<float>(real, imag, SAMPLE_COUNT, SAMPLE_RATE_HZ, weighingFactors);

Thanks for your help!

**Comment by HorstBaerbel** [comment]
Hi wilson3682. You need to use my [development version](https://github.com/HorstBaerbel/arduinoFFT) of the [ArduinoFFT](https://github.com/kosme/arduinoFFT/tree/develop) library and the [esp32-i2s-slm](https://github.com/HorstBaerbel/esp32-i2s-slm) project. You can't install this through the Arduino library manager, but need to do this by hand (uninstall the old one, download and copy the new one into the Arduino library folder).

**Comment by HorstBaerbel** [comment]
There's also some files still missing due to problems with the submodules. I will update the code in the next few days when I find time and respond here.

**Comment by wilson3682** [comment]
Thanks HorsBaerbel for your help! I deleted the arduinoFFT library installed through arduino and placed the dev library manually and now it compiles. Thanks again!

**Comment by HorstBaerbel** [comment]
I'd be surprised if it worked because you're probably missing some submodule code. I've updated the repo with the submodules and my current version of the code, but this is WIP. Will update the code in the next weeks. I've killed my ESP32 and am currently waiting for an replacement...
